version: '3.1'

services:

  app:
    image: ddsdeploy
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-crol2q23esus73c2rh9g-a.oregon-postgres.render.com/postgres_caba
      SPRING_DATASOURCE_USERNAME: postgres_caba_user
      SPRING_DATASOURCE_PASSWORD: BI33nIH9Njvoxppetwn72KQB9UivwP9i
      #SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      []